//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::KKSpeech.SpeechRecognizerListener.AuthorizationCallback))]
	public class PropertyProvider_KKSpeech_SpeechRecognizerListener_AuthorizationCallback : Unity.VisualScripting.SerializedPropertyProvider<KKSpeech.SpeechRecognizerListener.AuthorizationCallback>
	{
	}
}
